// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AskForSaveLocation() {
  return window['go']['main']['App']['AskForSaveLocation']();
}

export function ClickToSelectFiles() {
  return window['go']['main']['App']['ClickToSelectFiles']();
}

export function ConvertFiles(arg1, arg2) {
  return window['go']['main']['App']['ConvertFiles'](arg1, arg2);
}

export function GetFileType(arg1) {
  return window['go']['main']['App']['GetFileType'](arg1);
}
